### ISSUE TITLE
Permissions problem using ProjectByName

### ISSUE THREAD

**Issue by darksnow** [uselagoon/machinery#37]
I was looking to get a project ID, to determine is the project already exists, so used `client.Client().ProjectByName()`

It returns:
````
Error getting project project-name graphql: Unauthorized: You don't have permission to "view:user" on "ssh_key": {"users":["uuid-shaped-key"]}
`````
I changed this to use `ProjectByNameExtended()` and it worked perfectly. I've not really dug into this but I'm assuming it's an issue server side in GraphQL somewhere, and thought I should make you aware.

**Comment by darksnow** [comment]
Not sure if this is related but `ProjectByName()` includes the private keys for the project while `ProjectByNameExtended()` does not.

**Comment by shreddedbacon** [comment]
Yeah, as I said before in the lagoon-cli issue. You're using these libraries and tools outside of what we've provided as supported tooling (ie, lagoon-cli) before they're really ready to be used, so you're probably going to encounter a lot of things like this as you go.

You're probably going to encounter lots of permission issues purely because you won't have permission to do everything, and you need to have a good understanding of the library and lagoon rbac to know what you can and can't use. And some of what is in machinery was written for specific usecases within our services codebase that will work for our internal tools, but not general users.

Specifically, ProjectByName uses this https://github.com/uselagoon/machinery/blob/main/api/lagoon/client/_lgraphql/projects/projectByName.graphql and as you've found it recalls a lot of extra information that your user won't have access to, due to the way graphql works and the way lagoon has RBAC built, it is extremely difficult to create defined queries that are deep resolvers without potentially hitting permission issues.

The first error you got, is because if you look at the query file, you'll see that it retrieves groups and users, and those users ssh keys. Now, you're not allowed to do that, you aren't allowed to view other users ssh keys.
```
Error getting project project-name graphql: Unauthorized: You don't have permission to "view:user" on "ssh_key": {"users":["uuid-shaped-key"]}
```

The `ProjectByName` query in machinery can probably have those extra fields removed so that it can only retrieve information that won't be broken by RBAC. We'll need to review it, and anything we do, and maybe create a new one if anything we use uses it with the current fields.

You'll need to make sure you have an absolutely good understanding of what fields can and can't be retrieved as you build your tool, because not all roles in Lagoon can access things. If you build something as a user that has the role of `owner` for example, you may find it works fine for some things, but then if you get a user that has `maintainer` or `developer` to do something, they may hit a permission error. And if we eventually introduce custom roles, then it will be even more tricky, and you'll need to know the permission model of Lagoon even more.

This is why machinery is an extremely difficult library to manage for ALL roles/permissions, and this is why you'll probably encounter things like this fairly often.

---
> Not sure if this is related but ProjectByName() includes the private keys for the project while ProjectByNameExtended() does not.

Well, that is a different issue too. Most people don't need the privatekey, that is why `ProjectByNameExtended` doesn't have it. And also, most roles in Lagoon don't have permission to view the privatekey of a project either, which again is why `ProjectByNameExtended` doesn't include it

---

We're working on machinery fairly actively, but we're also open to pullrequests and contributions. If you feel that something can be improved, or done differently, feel free to submit PRs and we can review them too.
